---
title: "scBIOT in R"
output: html_document
---

See the v1.2.0 tutorials at https://scbiot.readthedocs.io/en/stable/.
```{r}
# rm(list=ls())
library(Seurat)
library(reticulate)
# devtools::install_github("satijalab/seurat-data")
# SeuratData::InstallData("ifnb")
library(SeuratData)
library(tidyverse)
```

Load and process pbmc data
```{r}
data("ifnb")
alldata <- UpdateSeuratObject(ifnb)
alldata[["pct_mt"]] <- PercentageFeatureSet(alldata, pattern = "^MT-")
alldata <- subset(alldata, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & pct_mt < 5)
```

## Converting Seurat object to AnnData
scBIOT relies on the [AnnData] object. 
```{r}
library(reticulate)
# devtools::install_github("cellgeni/sceasy")
library(sceasy)

sc <- import("scanpy", convert = FALSE)
scb <- import("scbiot", convert = FALSE)
```

```{r}
adata <- sceasy::convertFormat(alldata, from="seurat", to="anndata", main_layer="counts", drop_single_values=FALSE)
print(adata)

sceasy::convertFormat(
  alldata,
  from = "seurat",
  to = "anndata",
  main_layer = "counts",
  drop_single_values = FALSE,
  outFile = "ifnb.h5ad"   # <- this makes the .h5ad file
)
```

Create semi-supervised labels and run the v1.2.0 linear autoencoder
```{r}
np <- import("numpy", convert = FALSE)
adata$obs[["cell_type"]] <- adata$obs[["seurat_annotations"]]
adata$obs[["semi_cell_type"]] <- np$where(
  adata$obs[["stim"]]$astype("str")$eq("CTRL"),
  adata$obs[["cell_type"]],
  "Unknown"
)
adata$layers[["counts"]] <- adata$X$copy()

adata <- scb$pp$autoencoder(
  adata,
  input_key = "counts",
  out_key = "X_ae",
  batch_key = "stim",
  label_key = "semi_cell_type",
  unlabeled_category = "Unknown",
  n_top_genes = as.integer(2000),
  latent_dim = as.integer(30),
  max_epochs = as.integer(30),
  early_stop_patience = as.integer(5),
  random_state = as.integer(0)
)
```

Run supervised optimal transport and supBIOT label transfer
```{r}
res <- scb$ot$integrate(
  adata,
  obsm_key = "X_ae",
  batch_key = "stim",
  out_key = "X_supbiot",
  label_key = "semi_cell_type",
  unlabeled_category = "Unknown",
  random_state = as.integer(0)
)
adata   <-  res[[0]]
metrics <-  res[[1]]

adata <- scb$ot$supbiot(
  adata,
  use_rep = "X_supbiot",
  input_rep_key = "X_ae",
  label_key = "semi_cell_type",
  unlabeled_category = "Unknown",
  pred_label_key = "pred_cell_type",
  pred_conf_key = "pred_confidence",
  min_conf = 0,
  random_state = as.integer(0)
)
```
Run UMAP and Leiden clustering on the OT result
```{r}
sc$pp$neighbors(adata, use_rep='X_supbiot')
sc$tl$umap(adata)
sc$tl$leiden(adata, resolution=0.8, key_added='leiden_X_supbiot')
adata
```

```{r, fig.width=2.5, fig.height=2.5, dpi=300}
ot <- as.matrix(adata$obsm['X_umap'])
rownames(ot) = colnames(alldata)
alldata[["ot"]] <- CreateDimReducObject(embeddings = ot, key = "ot_umap_", assay = DefaultAssay(alldata))

DimPlot(alldata, reduction = "ot", group.by = "stim", label = TRUE) + ggtitle("Optimal Transport Integration")
```
Visualization
```{r, fig.width=3.5, fig.height=2.5, dpi=150}
DimPlot(alldata, reduction = "ot", group.by = "stim", label = TRUE) + ggtitle("scBIOT Integration")
```
Normalize data for feature plot
```{r}
alldata <- alldata %>% NormalizeData() %>% ScaleData() 
```

Feature plot
```{r, fig.width=12, fig.height=5, dpi=300}
FeaturePlot(alldata, features = c("SELL", "CREM", "CD8A", "GNLY", "CD79A", "FCGR3A", 
    "CCL2", "PPBP"), min.cutoff = "q9", pt.size = 0.2, ncol = 4)
```

```{r, fig.width=5, fig.height=5, dpi=150}
FeaturePlot(alldata, features = c("GNLY", "IFI6"), split.by = "stim", max.cutoff = 3, pt.size = 0.1, 
    cols = c("grey", "darkred"))
```

```{r}
info <- sessionInfo()
info$loadedOnly <- NULL
print(info, locale=FALSE)
```
