from __future__ import annotations

from typing import Any, Dict

Preset = Dict[str, Any]


_MODALITY_PRESETS: Dict[str, Preset] = {
    # Default settings used for integration of scRNA-seq
    "rna": {
        "obsm_key": "X_pca",
        "batch_key": "batch",
        "out_key": "X_ot",
        "reference": "union",
        "K_ref": 1024,
        "K_batch": 512,
        "reg": 0.03,
        "reg_m": 0.40,
        "sharpen": 0.15,
        "K_pseudo": 24,
        "pull": 0.75,
        "push": 0.30,
        "lambda0_hi": 0.50,
        "lambda0_lo": 0.35,
        "smin_bulk": 1.55,
        "smax_bulk": 1.65,
        "smin_bridge": 1.15,
        "smax_bridge": 1.25,
        "max_step_local": 1.0,
        "step_lo": 0.75,
        "step_hi": 0.95,
        "q_start": 0.80,
        "q_end": 0.90,
        "overlap0_lo": 0.60,
        "overlap0_hi": 0.70,
        "w_overlap": 0.20,
        "w_strain": 1.0,
        "penalty_gamma": 1.5,
        "use_gpu": True,
        "ot_backend": "torch",
        "verbose": True,
        # approximate ot and centroid ot
        "projector_strength": 0.5,
        "approximate_ot": False,
        "centroid_ot": False,
    },
    # Default settings used for supervised integration
    "supervised": {
        "obsm_key": "X_pca",
        "batch_key": "batch",
        "out_key": "X_ot",
        "reference": "union",
        "K_ref": 1024,
        "K_batch": 512,
        "reg": 0.03,
        "reg_m": 0.40,
        "sharpen": 0.,
        "K_pseudo": 15,
        "pull": 0.,
        "push": 0.,
        "lambda0_hi": 0.50,
        "lambda0_lo": 0.35,
        "smin_bulk": 0.75,
        "smax_bulk": 1.65,
        "smin_bridge": 0.85,
        "smax_bridge": 1.25,
        "max_step_local": 1.0,
        "step_lo": 0.75,
        "step_hi": 0.95,
        "q_start": 0.80,
        "q_end": 0.90,
        "overlap0_lo": 0.60,
        "overlap0_hi": 0.70,
        "w_overlap": 0.20,
        "w_strain": 1.0,
        "penalty_gamma": 1.5,        
        "use_gpu": True,
        "ot_backend": "torch",
        "verbose": True,
        # Prealign
        "prealign": "none",
        "prealign_strength": 0.1,
        "coral_eps": 1e-3,
        "prealign_max_points": 20000,
        "label_key": "semi_cell_type",
        "unlabeled_category": 'Unknown',
        # Supervised
        "lam_sup": 0.6,
        "lam_repulse": 0.2,
        # approximate ot and centroid ot
        "projector_strength": 1.0,
        "approximate_ot": False,
        "centroid_ot": False,
    },
    "spatial": {
        "obsm_key": "X_pca",
        "batch_key": "batch",
        "spatial_key": "spatial",
        "out_key": "X_geo_ot",
        "K_ref": 960,
        "K_batch": 384,
        "spatial_weight": 0.45,
        "laplacian_lambda": 0.35,
        "laplacian_k": 8,
        "reg": 0.03,
        "reg_m": 0.35,
        "max_step_local": 1.05,
        "k_local": 15,
        "k_eval": 30,
        "eval_subsample": 5000,
        "postscale": True,
        "use_gpu": True,
        "gpu_device": 0,
        "blend_alpha": 0.7,
        "bayesian_model": True,
        "bayes_prior_scale": 0.65,
        "bayes_obs_scale": 1.35,
        "bayes_min_posterior_weight": 0.15,
        "bayes_adaptive_precision": True,
        "verbose": True,
        # approximate ot and centroid ot
        "approximate_ot": False,
        "centroid_ot": False,
    },
    # Default settings used for integration of ATAC-seq
    "atac": {
        "obsm_key": "X_lsi",
        "batch_key": "batchname_all",
        "out_key": "scBIOT_OT",
        "reference": "largest",
        "K_ref": 960,
        "K_batch": 360,
        "reg": 0.036,
        "reg_m": 0.30,
        "sharpen": 0.12,
        "K_pseudo": 20,
        "pull": 0.72,
        "push": 0.22,
        "lambda0_hi": 0.58,
        "lambda0_lo": 0.42,
        "smin_bulk": 0.78,
        "smax_bulk": 1.50,
        "smin_bridge": 0.90,
        "smax_bridge": 1.16,
        "max_step_local": 0.80,
        "step_lo": 0.64,
        "step_hi": 0.82,
        "q_start": 0.78,
        "q_end": 0.885,
        "overlap0_lo": 0.64,
        "overlap0_hi": 0.73,
        "w_overlap": 0.22,
        "w_strain": 1.0,
        "penalty_gamma": 1.30,
        "use_gpu": True,
        "ot_backend": "torch",
        "verbose": True,
        # approximate ot and centroid ot
        "projector_strength": 0.10,
        "approximate_ot": False,
        "centroid_ot": False,
    },
    "paired": {
        "obsm_key": "X_pca",
        "view_key": "X_lsi",
        "batch_key": "batch",
        "out_key": "X_joint",        
        "K_ref": 1024,
        "K_batch": 512,
        "reg": 0.028,
        "reg_m": 0.40,
        "prior_strength": 1.0,
        "diag_mass": 0.2,
        "w_base": 0.5,
        "w_view": 0.5,
        "random_state": 0,
        "use_gpu": True,
        "gpu_device": 0,
        "ot_backend": "torch",
        "verbose": True,
        # approximate ot and centroid ot
        "projector_strength": 0.5,
        "approximate_ot": False,
        "centroid_ot": False,
    },
    # Default settings used for integration of cross-modalities/multiomics/disjoint datasets
    "anchor": {
        "obsm_key": "X_pca",
        "batch_key": "batch",
        "out_key": "X_ot",
        "reference": "union",
        "K_ref": 1024,
        "K_batch": 512,
        "reg": 0.03,
        "reg_m": 0.40,
        "sharpen": 0.15,
        "K_pseudo": 24,
        "pull": 0.75,
        "push": 0.30,
        "lambda0_hi": 0.50,
        "lambda0_lo": 0.35,
        "smin_bulk": 0.75,
        "smax_bulk": 1.65,
        "smin_bridge": 0.85,
        "smax_bridge": 1.25,
        "max_step_local": 1.0,
        "step_lo": 0.75,
        "step_hi": 0.95,
        "q_start": 0.80,
        "q_end": 0.90,
        "overlap0_lo": 0.60,
        "overlap0_hi": 0.70,
        "w_overlap": 0.20,
        "w_strain": 1.0,
        "penalty_gamma": 1.5,
        "use_gpu": True,
        "ot_backend": "torch",
        "verbose": True,
        # Prealign
        "prealign": "coral",
        "prealign_strength": 1.0,
        "coral_eps": 1e-3,
        "prealign_max_points": 20000,
        "label_key": "semi_cell_type",
        "unlabeled_category": 'Unknown',
        # Supervised
        "lam_sup": 0.60,
        "lam_repulse": 0.18,
        # approximate ot and centroid ot
        "projector_strength": 0.5,
        "approximate_ot": True,
        "centroid_ot": False,
    },
    # Default settings used for centroid-level OT (ultra-large datasets)
    "centroid": {
        "n_centroids_per_batch": 2048,
        "max_samples_per_batch": 500_000,
        "k_interp": 8,
        "chunk_size": 500_000,
        "use_gpu": True,
        "gpu_device": 0,
        "tmp_path": "/tmp/scbiot_X_supbiot.memmap",
        "centroid_ot": True

    },
}


def get_modality_preset(preset: str) -> Preset:
    key = preset.lower()
    try:
        return _MODALITY_PRESETS[key]
    except KeyError as exc:
        allowed = ", ".join(sorted(_MODALITY_PRESETS))
        raise ValueError(f"Unknown preset '{preset}'. Available presets: {allowed}") from exc
